---
title: "Course Schedules"
date: "Updated `r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## DA 3440: Data Science for Defense Analysis

<center>

```{r}
library(purrr)

ds4da_book_root <- "https://knapply.github.io/ds4da-book/"

ds4da_schedule <- tibble::tibble(
  Week = 1:5,
  Topic = c("Setting Up", "Data Analysis I", "Data Analysis II", "Data Analysis III",
            "R as a Programming Language"),
  `Book Section` = list(
    c("setup-r-and-rstudio", 
      "setup-coding-basics",
      "setup-projects",
      "setup-version-control",
      "setup-rmarkdown")
    ,
    c("da1-importing-data",
      "da1-data-frames",
      "da1-tidy-data",
      "da1-exporting-data")
    ,
    c("da2-text",
      "da2-dates-times")
    ,
    c("da3-relational-data")
    ,
    c("programming-objects",
      "programming-control-structures",
      "programming-functions",
      "programming-iteration")
  )
)


ds4da_schedule$`Book Section` <-  map_chr(ds4da_schedule$`Book Section`, ~ {
    no_prefix <- stringr::str_remove(.x, "^\\w+(?=-)")
    no_hyphens <- stringr::str_replace_all(no_prefix, "-", " ")
    title_case <- stringr::str_to_title(no_hyphens)
      
    res <- glue::glue(
      '-<a href="{ds4da_book_root}{.x}.html" target="_blank">{title_case}</a>'
    )
    
    stringr::str_flatten(res, "<br>")
  })


ds4da_schedule %>%
  DT::datatable(
    escape = FALSE, rownames = FALSE,
    filter = "top",
    options = list(
      autoWidth = TRUE,
      columnDefs = list(list(width = '10px', targets = 0)),
      dom = "ft", searchHighlight = TRUE, pageLength = nrow(ds4da_schedule)
    )
  ) %>% 
  widgetframe::frameWidget()
```

</center>

## Data Science for Practitioners

```{r}
ds4p_schedule <- tibble::tribble(
  ~Day,  ~Topic,
  1,     "Setting Up, Data Analysis I",
  2,     "Data Analysis II",
  3,     "Data Analysis III",
  4,     "Visualization - Going Deeper",
  5,     "Putting it all Together"
)

knitr::kable(ds4p_schedule)
```

